### ISSUE TITLE
Plugin not work on 1.18 spigot

### ISSUE THREAD

**Issue by FactoJanrenzo** [froobynooby/ViewDistanceTweaks#18]
[09:01:47 WARN]: Unexpected exception while parsing console command "vdt"
org.bukkit.command.CommandException: Cannot execute command 'vdt' in plugin ViewDistanceTweaks v1.4.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:808) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:771) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:512) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1478) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1266) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:315) ~[paper-1.18.1.jar:git-Paper-"e9947f8"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by froobynooby** [comment]
Hey, have you set `enabled: true` in the config?

**Comment by FactoJanrenzo** [comment]
Ahh.. That's why. Thanks
