### ISSUE TITLE
Error while disabling the plugin 

### ISSUE THREAD

**Issue by masmc05** [froobynooby/ViewDistanceTweaks#27]
https://www.toptal.com/developers/hastebin/vefuxasafe.properties

the error is only when disabling, there isn't any error besides that

**Comment by masmc05** [comment]
version 1.18.2

**Comment by masmc05** [comment]
```
[08:32:32 WARN]: java.net.SocketException: Socket closed
[08:32:32 INFO]: [ViewDistanceTweaks] Disabling ViewDistanceTweaks v1.5.0
[08:32:32 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:222)
[08:32:32 WARN]:        at java.base/java.net.DatagramSocket.send(DatagramSocket.java:664)
[08:32:32 WARN]:        at plasmovoice-server-1.0.8.jar//su.plo.voice.socket.SocketServerUDP.sendTo(SocketServerUDP.java:74)
[08:32:32 WARN]:        at plasmovoice-server-1.0.8.jar//su.plo.voice.socket.SocketServerUDPQueue.keepAlive(SocketServerUDPQueue.java:144)
[08:32:32 WARN]:        at plasmovoice-server-1.0.8.jar//su.plo.voice.socket.SocketServerUDPQueue.run(SocketServerUDPQueue.java:24)
[08:32:32 WARN]: Caused by: java.nio.channels.ClosedChannelException
[08:32:32 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.ensureOpen(DatagramChannelImpl.java:267)
[08:32:32 WARN]:        at java.base/sun.nio.ch.DatagramChannelImpl.blockingSend(DatagramChannelImpl.java:850)
[08:32:32 WARN]:        at java.base/sun.nio.ch.DatagramSocketAdaptor.send(DatagramSocketAdaptor.java:218)
[08:32:32 WARN]:        ... 4 more
[08:32:32 ERROR]: Error occurred while disabling ViewDistanceTweaks v1.5.0 (Is it up to date?)
com.froobworld.viewdistancetweaks.lib.joor.ReflectException: java.lang.reflect.InvocationTargetException
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.on(Reflect.java:914) ~[ViewDistanceTweaks-1.5.0.jar:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.call(Reflect.java:575) ~[ViewDistanceTweaks-1.5.0.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager$ViewDistancePacketModifier.remove(ClientViewDistanceManager.java:126) ~[ViewDistanceTweaks-1.5.0.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.shutdown(ClientViewDistanceManager.java:44) ~[ViewDistanceTweaks-1.5.0.jar:?]
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onDisable(ViewDistanceTweaks.java:65) ~[ViewDistanceTweaks-1.5.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:515) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:493) ~[purpur-1.18.2.jar:git-Purpur-1605]
        at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:984) ~[purpur-1.18.2.jar:git-Purpur-1605]
        at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:842) ~[purpur-1.18.2.jar:git-Purpur-1605]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1297) ~[purpur-1.18.2.jar:git-Purpur-1605]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1605]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.on(Reflect.java:910) ~[ViewDistanceTweaks-1.5.0.jar:?]
        ... 15 more
Caused by: java.util.NoSuchElementException: vdt_packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1073) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423) ~[netty-all-4.1.68.Final.jar:4.1.68.Final]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.on(Reflect.java:910) ~[ViewDistanceTweaks-1.5.0.jar:?]
        ... 15 more
```
so hastebin won't delete this

**Comment by oskarkk** [comment]
I get similar error when the plugin isn't configured:

```
[05:15:09 Server thread/WARN] ViewDistanceTweaks must be configured before it can be enabled. Edit the config.yml file in the plugin's data folder, setting the 'enabled' option to true when you are done, then reload or restart the server.
[05:15:09 Server thread/INFO] Disabling ViewDistanceTweaks v1.5.0
[05:15:09 Server thread/ERROR] Error occurred while disabling ViewDistanceTweaks v1.5.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.shutdown()" because "this.clientViewDistanceManager" is null
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onDisable(ViewDistanceTweaks.java:65) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:40) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by masmc05** [comment]
> I get similar error when the plugin isn't configured:
> 
> ```
> [05:15:09 Server thread/WARN] ViewDistanceTweaks must be configured before it can be enabled. Edit the config.yml file in the plugin's data folder, setting the 'enabled' option to true when you are done, then reload or restart the server.
> [05:15:09 Server thread/INFO] Disabling ViewDistanceTweaks v1.5.0
> [05:15:09 Server thread/ERROR] Error occurred while disabling ViewDistanceTweaks v1.5.0 (Is it up to date?)
> java.lang.NullPointerException: Cannot invoke "com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.shutdown()" because "this.clientViewDistanceManager" is null
>         at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onDisable(ViewDistanceTweaks.java:65) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:40) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:666) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-"aab1f8a"]
>         at java.lang.Thread.run(Thread.java:833) [?:?]
> ```

you can read the message, it says it won't work until it's connfigured

**Comment by oskarkk** [comment]
Yes, but it still shouldn't have NullPointerException. If shutting down the plugin is the intended behavior, it should shut down cleanly, not print errors. Both yours and my errors could be caused by some bug in the shutdown code.
