### ISSUE TITLE
Does not work anymore (1.18.2)

### ISSUE THREAD

**Issue by BrandonT80** [froobynooby/ViewDistanceTweaks#29]
Plugin no longer works in 1.18.2. Produces the below error:

[15:47:40] [Server thread/ERROR]: [ViewDistanceTweaks] Exception while loading configuration:
[15:47:40] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "com.froobworld.viewdistancetweaks.lib.nabconfiguration.utils.InstantFallbackConfigurationSection.getSection(String, String)" because "this.fallbackSection" is null
[15:47:40] [Server thread/WARN]: 	at ViewDistanceTweaks-1.5.0.jar//com.froobworld.viewdistancetweaks.lib.nabconfiguration.utils.InstantFallbackConfigurationSection.getSection(InstantFallbackConfigurationSection.java:36)
[15:47:40] [Server thread/WARN]: 	at ViewDistanceTweaks-1.5.0.jar//com.froobworld.viewdistancetweaks.lib.nabconfiguration.ConfigSectionPopulator.populate(ConfigSectionPopulator.java:46)
[15:47:40] [Server thread/WARN]: 	at ViewDistanceTweaks-1.5.0.jar//com.froobworld.viewdistancetweaks.lib.nabconfiguration.NabConfiguration.load(NabConfiguration.java:31)
[15:47:40] [Server thread/WARN]: 	at ViewDistanceTweaks-1.5.0.jar//com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:29)
[15:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[15:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[15:47:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501)
[15:47:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559)
[15:47:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473)
[15:47:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664)
[15:47:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[15:47:40] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:316)
[15:47:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1163)
[15:47:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[15:47:40] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:47:40] [Server thread/INFO]: [ViewDistanceTweaks] Disabling ViewDistanceTweaks v1.5.0
[15:47:40] [Server thread/ERROR]: Error occurred while disabling ViewDistanceTweaks v1.5.0 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.shutdown()" because "this.clientViewDistanceManager" is null
	at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onDisable(ViewDistanceTweaks.java:65) ~[ViewDistanceTweaks-1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:33) ~[ViewDistanceTweaks-1.5.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-274]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-274]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BrandonT80** [comment]
https://paste.gg/p/anonymous/4af4758120c448aabe8e2756a1698e50

**Comment by froobynooby** [comment]
Same deal as https://github.com/froobynooby/FarmControl/issues/24 - if you only want the plugin active in that one world you'd need something like this: https://paste.gg/p/anonymous/f54a3dc32eb2436a9a0eccc8cfd50799

**Comment by BrandonT80** [comment]
That did not correct the error sadly

**Comment by froobynooby** [comment]
Are you sure you copied the config over correctly? I launched up the plugin with the same config and it's not giving errors any more
