### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by thatmirc** [froobynooby/ViewDistanceTweaks#33]
Placed this issue to track when the plugin is updated. 

Please update to 1.19

**Comment by thatmirc** [comment]
[16:55:33] [Server thread/INFO]: [ViewDistanceTweaks] Enabling ViewDistanceTweaks v1.5.0
[16:55:33] [Server thread/ERROR]: Error occurred while enabling ViewDistanceTweaks v1.5.0 (Is it up to date?)
java.lang.IllegalStateException: Incompatible version
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.getProperSimulationDistance(SpigotViewDistanceSyncer.java:55) ~[?:?]
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.syncSpigotViewDistances(SpigotViewDistanceSyncer.java:18) ~[?:?]
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.syncSpigotViewDistances(SpigotViewDistanceSyncer.java:27) ~[?:?]
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:43) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:513) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:427) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:582) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:401) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:966) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3513-Spigot-fa893f0-576a037]
        at java.lang.Thread.run(Thread.java:833) [?:?]
