### ISSUE TITLE
Bug: No simulation distance hook

### ISSUE THREAD

**Issue by stitchinger** [froobynooby/ViewDistanceTweaks#36]
Hello,
trying your plugin(1.5.1) with 1.18.2.
I get this error on startup:
```
[11:30:51 INFO]: [ViewDistanceTweaks] Enabling ViewDistanceTweaks v1.5.1
[11:30:51 ERROR]: Error occurred while enabling ViewDistanceTweaks v1.5.1 (Is it up to date?)
java.lang.IllegalStateException: No simulation distance hook is available. Incompatible version?
	at com.froobworld.viewdistancetweaks.HookManager.init(HookManager.java:62) ~[?:?]
	at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:518) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:432) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:612) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:263) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1007) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3498-Spigot-b081915-10ba1be]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by froobynooby** [comment]
Thanks for reporting the bug - I've uploaded a new version to Spigot which fixes it
