### ISSUE TITLE
Incompatible with 1.19.3

### ISSUE THREAD

**Issue by gamerover98** [froobynooby/ViewDistanceTweaks#40]
Hello, the plugin won't start on Spigot 1.19.3:

```JAVA
[20:54:25] [Server thread/ERROR]: Error occurred while enabling ViewDistanceTweaks v1.5.3 (Is it up to date?)
java.lang.IllegalStateException: Incompatible version
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.getProperSimulationDistance(SpigotViewDistanceSyncer.java:62) ~[?:?]
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.syncSpigotViewDistances(SpigotViewDistanceSyncer.java:18) ~[?:?]
        at com.froobworld.viewdistancetweaks.util.SpigotViewDistanceSyncer.syncSpigotViewDistances(SpigotViewDistanceSyncer.java:27) ~[?:?]
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:55) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:587) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3616-Spigot-d90018e-eecb4c0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

```

Server info:
```
[20:56:26] [Server thread/INFO]: This server is running CraftBukkit version 3616-Spigot-d90018e-eecb4c0 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)
[20:56:26] [Server thread/INFO]: Checking version, please wait...
[20:56:26] [Thread-40/INFO]: You are running the latest version
```

**Comment by froobynooby** [comment]
Fixed in 482f1376d52250ff82ac8a78e93795c26b37fd98
