### ISSUE TITLE
java.lang.NoSuchMethodException on PlayerJoinEvent

### ISSUE THREAD

**Issue by cpuschma** [froobynooby/ViewDistanceTweaks#43]
Hi,

after upgrading a PaperMC server to 1.19.4, the following exception occurs when I join the server:
``` [17:00:19 INFO]: UUID of player Nevo2 is e2d4e4a7-6bcc-40d5-bd40-0a1735aee994
[17:00:20 ERROR]: Could not pass event PlayerJoinEvent to ViewDistanceTweaks v1.5.4
com.froobworld.viewdistancetweaks.lib.joor.ReflectException: java.lang.NoSuchMethodException: No similar method pipeline with params [] could be found on type double.
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.call(Reflect.java:585) ~[ViewDistanceTweaks-1.5.4.jar:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.call(Reflect.java:528) ~[ViewDistanceTweaks-1.5.4.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager$ViewDistancePacketModifier.inject(ClientViewDistanceManager.java:104) ~[ViewDistanceTweaks-1.5.4.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.onPlayerJoin(ClientViewDistanceManager.java:78) ~[ViewDistanceTweaks-1.5.4.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:git-Paper-466]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.19.4.jar:git-Paper-466]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.19.4.jar:git-Paper-466]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:592) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1396) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.4.jar:git-Paper-466]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-466]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NoSuchMethodException: No similar method pipeline with params [] could be found on type double.
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.similarMethod(Reflect.java:652) ~[ViewDistanceTweaks-1.5.4.jar:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.call(Reflect.java:582) ~[ViewDistanceTweaks-1.5.4.jar:?]
        ... 21 more
```
This happens for all players and only when joining the server. Has anyone else experienced this error yet? The following plugins are installed on the server:
```
FastAsyncWorldEdit-Bukkit-2.6.0-SNAPSHOT-391.jar
tabtps-spigot-1.3.16.jar
ViaBackwards-4.6.1.jar
ViaVersion-4.6.1.jar
ViewDistanceTweaks-1.5.4.jar
worldguard-bukkit-7.0.7-dist.jar
```

**Comment by maxfire2008** [comment]
This also happens for me on 1.19.4

My plugins:
```
[13:17:33 INFO]: Server Plugins (13):
[13:17:33 INFO]: Bukkit Plugins:
[13:17:33 INFO]:  - CoreProtect, DriveBackupV2, Essentials, EssentialsChat, EssentialsSpawn, LuckPerms, NoEncryption, OpenInv, PlaceholderAPI, SimpleScore
[13:17:33 INFO]:  ViewDistanceTweaks, VillagerSaver, Waypoints
```

**Comment by cpuschma** [comment]
Thank you for your work, @froobynooby, really! Your plugin and consistent work really helped me alot! ❤️
