### ISSUE TITLE
Error on Player Join on 1.20.2

### ISSUE THREAD

**Issue by FireController1847** [froobynooby/ViewDistanceTweaks#50]
I imagine 1.20.2 is still in development, but here's the current error report when any player joins:
```
[22:32:53 ERROR]: Could not pass event PlayerJoinEvent to ViewDistanceTweaks v1.5.6
com.froobworld.viewdistancetweaks.lib.joor.ReflectException: com.froobworld.viewdistancetweaks.lib.joor.ReflectException: java.lang.NoSuchFieldException: m
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.field(Reflect.java:450) ~[ViewDistanceTweaks-1.5.6.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager$ViewDistancePacketModifier.inject(ClientViewDistanceManager.java:109) ~[ViewDistanceTweaks-1.5.6.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.onPlayerJoin(ClientViewDistanceManager.java:84) ~[ViewDistanceTweaks-1.5.6.jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:git-Paper-223]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.2.jar:git-Paper-223]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.2.jar:git-Paper-223]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:325) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.network.ServerConfigurationPacketListenerImpl.handleConfigurationFinished(ServerConfigurationPacketListenerImpl.java:130) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.handle(ServerboundFinishConfigurationPacket.java:18) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.network.protocol.configuration.ServerboundFinishConfigurationPacket.a(ServerboundFinishConfigurationPacket.java:9) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1324) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1301) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1294) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1272) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1160) ~[paper-1.20.2.jar:git-Paper-223]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-223]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: com.froobworld.viewdistancetweaks.lib.joor.ReflectException: java.lang.NoSuchFieldException: m
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.field0(Reflect.java:474) ~[ViewDistanceTweaks-1.5.6.jar:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.field(Reflect.java:446) ~[ViewDistanceTweaks-1.5.6.jar:?]
        ... 26 more
Caused by: java.lang.NoSuchFieldException: m
        at java.lang.Class.getField(Class.java:2117) ~[?:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.field0(Reflect.java:459) ~[ViewDistanceTweaks-1.5.6.jar:?]
        at com.froobworld.viewdistancetweaks.lib.joor.Reflect.field(Reflect.java:446) ~[ViewDistanceTweaks-1.5.6.jar:?]
        ... 26 more
```

Absolutely love this plugin, makes it so our server doesn't destroy itself during peak hours! Tysm!

**Comment by froobynooby** [comment]
Fixed in 1df8c7731d97f2fbbdf74510fc926277d13effbc - you can download the latest build here https://ci.froobworld.com/job/ViewDistanceTweaks/
