### ISSUE TITLE
[BUG] Plugin stop working under Paper with CB packge relocation

### ISSUE THREAD

**Issue by YuanYuanOwO** [froobynooby/ViewDistanceTweaks#56]
https://forums.papermc.io/threads/important-dev-psa-future-removal-of-cb-package-relocation.1106/

```
[20:07:51 INFO]: [ViewDistanceTweaks] Enabling ViewDistanceTweaks v1.5.7
[20:07:51 INFO]: [ViewDistanceTweaks] Using PaperSimulationDistanceHook for the simulation distance hook.
[20:07:51 INFO]: [ViewDistanceTweaks] Using PaperViewDistanceHook for the view distance hook.
[20:07:51 INFO]: [ViewDistanceTweaks] Using PaperTickHook for the tick hook.
[20:07:51 ERROR]: Error occurred while enabling ViewDistanceTweaks v1.5.7 (Is it up to date?)
java.lang.NumberFormatException: For input string: "org.bukkit.craftbukkit"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
        at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
        at com.froobworld.viewdistancetweaks.util.NmsUtils.getMajorVersion(NmsUtils.java:31) ~[ViewDistanceTweaks-1.5.7.jar:?]
        at com.froobworld.viewdistancetweaks.limiter.ClientViewDistanceManager.init(ClientViewDistanceManager.java:32) ~[ViewDistanceTweaks-1.5.7.jar:?]
        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:50) ~[ViewDistanceTweaks-1.5.7.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by YuanYuanOwO** [comment]
i think it's solved by latest dev build.  
hope will update to 1.20.5+ support.anyway thank for dev:)
