### ISSUE TITLE
Can't use plugin - logs inside

### ISSUE THREAD

**Issue by M1ghty-boy** [froobynooby/ViewDistanceTweaks#7]
This server is running Paper version git-Paper-250 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

Never used this plugin before

Plugins (23): AdvancedPortals, Citizens, CoreProtect, Curses, Essentials, EssentialsChat, EssentialsSpawn, ImageOnMap, InventoryRollback, Invsee*, Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, Multiverse-SignPortals, PermissionsEx*, ProtocolLib, SuperVanish, VarLight, ViewDistanceTweaks, Vivecraft-Spigot-Extensions, WorldEdit, WorldGuard

Here are the logs:

```
[01:23:28 INFO]: [ViewDistanceTweaks] Enabling ViewDistanceTweaks v1.2.4
[01:23:28 ERROR]: [ViewDistanceTweaks] Exception while loading configuration:
[01:23:28 WARN]: java.lang.NullPointerException
[01:23:28 WARN]:        at com.froobworld.viewdistancetweaks.lib.nabconfiguration.utils.InstantFallbackConfigurationSection.getSection(InstantFallbackConfigurationSection.java:36)
[01:23:28 WARN]:        at com.froobworld.viewdistancetweaks.lib.nabconfiguration.ConfigSectionPopulator.populate(ConfigSectionPopulator.java:44)
[01:23:28 WARN]:        at com.froobworld.viewdistancetweaks.lib.nabconfiguration.NabConfiguration.load(NabConfiguration.java:31)
[01:23:28 WARN]:        at com.froobworld.viewdistancetweaks.ViewDistanceTweaks.onEnable(ViewDistanceTweaks.java:28)
[01:23:28 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[01:23:28 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[01:23:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[01:23:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[01:23:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[01:23:28 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[01:23:28 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[01:23:28 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[01:23:28 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[01:23:28 WARN]:        at java.lang.Thread.run(Unknown Source)
[01:23:28 INFO]: [ViewDistanceTweaks] Disabling ViewDistanceTweaks v1.2.4
```

**Comment by froobynooby** [comment]
That error is saying there's something wrong with your config. If you can share your config here I could tell you what's wrong

Alternatively, you can delete your config and let it regenerate

**Comment by froobynooby** [comment]
I'm just going to close this issue because of inactivity. If you're still having the problem you'll need to provide a copy of your config.yml
